name = "charmnest"
main = "src/cloudflare/worker.mjs"
compatibility_date = "2026-07-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "charmnest"
database_id = "0f6c15c1-c734-473f-85a9-cb091c552374"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "charmnest-media"

[vars]
APP_ENV = "production"
PUBLIC_SITE_NAME = "CharmNest"
