import { DEFAULT_SETTINGS } from '../core/constants.mjs';
import { mergeSettings, newId, nowIso, serializeDrop, serializeOrder, serializePhoto } from '../core/store-utils.mjs';

export class CloudflareStore {
  constructor(env){this.db=env.DB;this.media=env.MEDIA;}
  async init(){const now=nowIso();for(const [k,v] of Object.entries(DEFAULT_SETTINGS))await this.db.prepare('INSERT OR IGNORE INTO settings(key,value,updated_at) VALUES(?,?,?)').bind(k,String(v),now).run();}
  async getSettings(){const {results=[]}=await this.db.prepare('SELECT key,value FROM settings').all();return mergeSettings(results);}
  async updateSettings(patch,actor){const now=nowIso();for(const [k,v] of Object.entries(patch))await this.db.prepare('INSERT INTO settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind(k,String(v),now).run();await this.log(actor,'settings.update','settings','',patch);return this.getSettings();}
  async photosForDrop(id,includePrivate){const sql=`SELECT p.*,dp.position,dp.is_cover FROM photos p JOIN drop_photos dp ON dp.photo_id=p.id WHERE dp.drop_id=? ${includePrivate?'':"AND p.status='approved' AND p.no_faces_confirmed=1"} ORDER BY dp.is_cover DESC,dp.position`;const {results=[]}=await this.db.prepare(sql).bind(id).all();return results.map(r=>({...serializePhoto(r),isCover:Boolean(r.is_cover),position:r.position}));}
  async listDrops({includePrivate=false}={}){const sql=includePrivate?'SELECT * FROM drops ORDER BY updated_at DESC':"SELECT * FROM drops WHERE status IN ('published','sold-out') ORDER BY published_at DESC,updated_at DESC";const {results=[]}=await this.db.prepare(sql).all();return Promise.all(results.map(async r=>serializeDrop(r,await this.photosForDrop(r.id,includePrivate))));}
  async getCurrentDrop(){const row=await this.db.prepare("SELECT * FROM drops WHERE status IN ('published','sold-out') ORDER BY CASE status WHEN 'published' THEN 0 ELSE 1 END,published_at DESC,updated_at DESC LIMIT 1").first();return row?serializeDrop(row,await this.photosForDrop(row.id,false)):null;}
  async getDrop(id,{includePrivate=true}={}){const row=await this.db.prepare('SELECT * FROM drops WHERE id=?').bind(id).first();return row?serializeDrop(row,await this.photosForDrop(id,includePrivate)):null;}
  async createDrop(d,a){const id=newId('drop'),now=nowIso();await this.db.prepare(`INSERT INTO drops(id,name,slug,month,year,headline,public_notes,private_notes,colors_json,color_hexes_json,featured_charm,beaded_available,braided_available,quantity,school_price_cents,custom_price_cents,online_price_min_cents,online_price_max_cents,release_date,end_date,tiktok_url,etsy_url,status,created_by,created_at,updated_at,published_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,d.name,d.slug,d.month,d.year,d.headline,d.publicNotes,d.privateNotes,JSON.stringify(d.colors),JSON.stringify(d.colorHexes),d.featuredCharm,Number(d.beadedAvailable),Number(d.braidedAvailable),d.quantity,d.schoolPriceCents,d.customPriceCents,d.onlinePriceMinCents,d.onlinePriceMaxCents,d.releaseDate,d.endDate,d.tiktokUrl,d.etsyUrl,d.status,a.username,now,now,d.status==='published'?now:null).run();await this.log(a,'drop.create','drop',id,{name:d.name,status:d.status});return this.getDrop(id);}
  async updateDrop(id,d,a){if(!await this.getDrop(id))return null;const now=nowIso();await this.db.prepare(`UPDATE drops SET name=?,slug=?,month=?,year=?,headline=?,public_notes=?,private_notes=?,colors_json=?,color_hexes_json=?,featured_charm=?,beaded_available=?,braided_available=?,quantity=?,school_price_cents=?,custom_price_cents=?,online_price_min_cents=?,online_price_max_cents=?,release_date=?,end_date=?,tiktok_url=?,etsy_url=?,status=?,updated_at=?,published_at=CASE WHEN ?='published' AND published_at IS NULL THEN ? ELSE published_at END WHERE id=?`).bind(d.name,d.slug,d.month,d.year,d.headline,d.publicNotes,d.privateNotes,JSON.stringify(d.colors),JSON.stringify(d.colorHexes),d.featuredCharm,Number(d.beadedAvailable),Number(d.braidedAvailable),d.quantity,d.schoolPriceCents,d.customPriceCents,d.onlinePriceMinCents,d.onlinePriceMaxCents,d.releaseDate,d.endDate,d.tiktokUrl,d.etsyUrl,d.status,now,d.status,now,id).run();await this.log(a,'drop.update','drop',id,{status:d.status});return this.getDrop(id);}
  async setDropStatus(id,status,a){const now=nowIso();const r=await this.db.prepare("UPDATE drops SET status=?,updated_at=?,published_at=CASE WHEN ?='published' THEN COALESCE(published_at,?) ELSE published_at END WHERE id=?").bind(status,now,status,now,id).run();if(!r.meta.changes)return null;await this.log(a,'drop.status','drop',id,{status});return this.getDrop(id);}
  async listPhotos({includePrivate=true}={}){const sql=includePrivate?'SELECT * FROM photos ORDER BY created_at DESC':"SELECT * FROM photos WHERE status='approved' AND no_faces_confirmed=1 ORDER BY created_at DESC";const {results=[]}=await this.db.prepare(sql).all();return results.map(serializePhoto);}
  async getPhoto(id){const row=await this.db.prepare('SELECT * FROM photos WHERE id=?').bind(id).first();return row?serializePhoto(row):null;}
  async savePhoto({meta,variants},a){const id=newId('photo'),ext=meta.mimeType==='image/png'?'png':meta.mimeType==='image/webp'?'webp':'jpg',originalKey=`originals/${id}.${ext}`,webKey=`web/${id}.webp`,thumbKey=`thumbs/${id}.webp`;await Promise.all([this.media.put(originalKey,variants.original,{httpMetadata:{contentType:meta.mimeType}}),this.media.put(webKey,variants.web,{httpMetadata:{contentType:'image/webp'}}),this.media.put(thumbKey,variants.thumb,{httpMetadata:{contentType:'image/webp'}})]);const now=nowIso();await this.db.prepare('INSERT INTO photos(id,original_key,web_key,thumb_key,original_name,mime_type,size_bytes,alt_text,caption,no_faces_confirmed,status,uploaded_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,originalKey,webKey,thumbKey,meta.originalName,meta.mimeType,variants.original.length,meta.altText,meta.caption,Number(meta.noFacesConfirmed),'pending',a.username,now).run();await this.log(a,'photo.upload','photo',id,{});return this.getPhoto(id);}
  async approvePhoto(id,decision,a){const status=decision==='approve'?'approved':decision==='reject'?'rejected':'archived',now=nowIso();const r=await this.db.prepare('UPDATE photos SET status=?,approved_by=?,approved_at=? WHERE id=?').bind(status,a.username,now,id).run();if(!r.meta.changes)return null;await this.log(a,`photo.${status}`,'photo',id,{});return this.getPhoto(id);}
  async attachPhoto(dropId,photoId,{isCover=false}={},a){if(isCover)await this.db.prepare('UPDATE drop_photos SET is_cover=0 WHERE drop_id=?').bind(dropId).run();await this.db.prepare('INSERT INTO drop_photos(drop_id,photo_id,position,is_cover) VALUES(?,?,COALESCE((SELECT MAX(position)+1 FROM drop_photos WHERE drop_id=?),0),?) ON CONFLICT(drop_id,photo_id) DO UPDATE SET is_cover=excluded.is_cover').bind(dropId,photoId,dropId,Number(isCover)).run();await this.log(a,'drop.photo.attach','drop',dropId,{photoId,isCover});return this.getDrop(dropId);}
  async getMedia(key){const obj=await this.media.get(key);if(!obj)return null;return{bytes:new Uint8Array(await obj.arrayBuffer()),type:obj.httpMetadata?.contentType||'application/octet-stream'};}
  async createOrder(d){const id=newId('order'),now=nowIso();await this.db.prepare('INSERT INTO orders(id,first_name,contact_email,bracelet_style,quantity,colors_json,charm,name_word,size,needed_by,gift_packaging,notes,estimated_cents,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,d.firstName,d.contactEmail,d.braceletStyle,d.quantity,JSON.stringify(d.colors),d.charm,d.nameWord,d.size,d.neededBy,Number(d.giftPackaging),d.notes,d.estimatedCents,'new',now,now).run();await this.log({username:'public',role:'public'},'order.create','order',id,{});const row=await this.db.prepare('SELECT * FROM orders WHERE id=?').bind(id).first();return serializeOrder(row,false);}
  async listOrders({includeEmail=false}={}){const {results=[]}=await this.db.prepare('SELECT * FROM orders ORDER BY created_at DESC').all();return results.map(r=>serializeOrder(r,includeEmail));}
  async updateOrderStatus(id,status,a){const now=nowIso(),r=await this.db.prepare('UPDATE orders SET status=?,updated_at=? WHERE id=?').bind(status,now,id).run();if(!r.meta.changes)return null;await this.log(a,'order.status','order',id,{status});return serializeOrder(await this.db.prepare('SELECT * FROM orders WHERE id=?').bind(id).first(),true);}
  async listActivity(limit=100){const {results=[]}=await this.db.prepare('SELECT * FROM activity_log ORDER BY created_at DESC LIMIT ?').bind(limit).all();return results.map(r=>({...r,details:JSON.parse(r.details_json||'{}')}));}
  async log(a,action,type,id,details={}){await this.db.prepare('INSERT INTO activity_log(id,actor,role,action,entity_type,entity_id,details_json,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(newId('act'),a.username||'system',a.role||'system',action,type,id||'',JSON.stringify(details),nowIso()).run();}
  async checkLoginLimit(key){const row=await this.db.prepare('SELECT * FROM login_attempts WHERE client_key=?').bind(key).first();if(!row?.locked_until)return{allowed:true};const t=Date.parse(row.locked_until);return t>Date.now()?{allowed:false,retryAfter:Math.ceil((t-Date.now())/1000)}:{allowed:true};}
  async recordLogin(key,success){if(success){await this.db.prepare('DELETE FROM login_attempts WHERE client_key=?').bind(key).run();return;}const cur=await this.db.prepare('SELECT * FROM login_attempts WHERE client_key=?').bind(key).first(),failed=(cur?.failed_count||0)+1,now=nowIso(),lock=failed>=5?new Date(Date.now()+15*60*1000).toISOString():null;await this.db.prepare('INSERT INTO login_attempts(client_key,failed_count,first_failed_at,locked_until,last_attempt_at) VALUES(?,?,?,?,?) ON CONFLICT(client_key) DO UPDATE SET failed_count=excluded.failed_count,locked_until=excluded.locked_until,last_attempt_at=excluded.last_attempt_at').bind(key,failed,cur?.first_failed_at||now,lock,now).run();}
}
